import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { ClipboardCheck, BrainCircuit, Activity } from "lucide-react"
import prisma from "@/lib/db/prisma"

export const instant = false

export default async function TestCasesPage() {
  const project = await prisma.project.findFirst({
    orderBy: { createdAt: 'desc' }
  });

  if (!project) return <div>No project found</div>;

  const testCases = await prisma.testCase.findMany({
    where: { projectId: project.id },
    include: {
      requirement: true
    }
  })

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">AI Test Cases</h1>
        <p className="text-muted-foreground mt-2">
          Test cases automatically generated by AIVAR based on extracted requirements.
        </p>
      </div>

      {testCases.length === 0 ? (
        <Card className="border-dashed bg-muted/30">
          <CardContent className="flex flex-col items-center justify-center p-12 text-center">
            <BrainCircuit className="h-12 w-12 text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold">No test cases generated yet</h3>
            <p className="text-sm text-muted-foreground mt-2 max-w-md">
              AIVAR generates test cases dynamically when you upload an SRS document. Upload a document to see your test cases here.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 gap-4">
          {testCases.map(tc => (
            <Card key={tc.id}>
              <CardHeader className="py-4">
                <CardTitle className="text-lg flex items-center space-x-2">
                  <ClipboardCheck className="h-5 w-5 text-primary" />
                  <span>{tc.title}</span>
                </CardTitle>
                <CardDescription>Generated for Requirement: {tc.requirement.reqId}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="bg-muted p-4 rounded-md">
                  <p className="text-sm font-medium mb-2">Steps:</p>
                  <p className="text-sm text-muted-foreground whitespace-pre-wrap">{tc.steps}</p>
                </div>
                <div className="mt-4 flex items-center space-x-2">
                  <Activity className="h-4 w-4 text-muted-foreground" />
                  <span className="text-sm font-medium">Expected Result:</span>
                  <span className="text-sm text-muted-foreground">{tc.expectedResult}</span>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
